name: m1

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Compile and run tests
      run: |
        gcc -o stats stats.c test_qa.c
        ./stats

