name: Test Course1

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the workflow

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [HOST] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean Build
        run: make clean
        working-directory: assessments/course1

      - name: Compile and Run
        run: |
          make PLATFORM=${{ matrix.platform }} VERBOSE=1 COURSE1=1
        working-directory: assessments/course1 # specify the directory where the Makefile is located

      - name: Check Test Results
        run: |
          echo "Checking test results"
          if ./Course1.out | grep -q "FAILED: 0 / 8"; then
            echo "All tests passed!"
          else
            echo "Some tests failed!"
            exit 1 
          fi
