name: Test Course1

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [HOST]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean Build
        run: make clean
        working-directory: assessments/course1  # Execute 'make clean' in this directory

      - name: Compile and Run
        run: |
          make PLATFORM=${{ matrix.platform }} VERBOSE=1 COURSE=1
          if ./Course1.out | grep -q "FAILED: 0 / 8"; then
            echo "All tests passed!"
          else
            echo "Some tests failed!"
            exit 1 
          fi
        working-directory: assessments/course1  # Execute 'make' and './Course1.out' in this directory
