name: Test Course1

on:
  push:
    branches:
      - main  

jobs:
  build_and_test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        platform: [HOST, MSP432] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Compile and Run
        run: |
          make PLATFORM=${{ matrix.platform }} VERBOSE=1 COURSE=1
          # If running on MSP432, capture output from the serial port

      - name: Check Test Results
        # Analyze the output to check for the PASSED/FAILED messages
        run: |
          test_output=$(cat output.txt) # Or however you capture output
          echo "$test_output"
          if echo "$test_output" | grep -q "FAILED: 0 / 8"; then
            echo "All tests passed!"
          else
            echo "Some tests failed!"
            exit 1  # Mark the workflow as failed
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always() 
        with:
          name: test-results-${{ matrix.platform }}
          path: output.txt
