name: m1

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Compile and run stats.c
      run: |
        gcc -o stats assessments/m1/stats.c -lm
        ./stats
